pipeline {
    agent any

    parameters {
      string(name: 'version', defaultValue: '0.1', description: '')
      choice(name: 'deploymentServer', choices: ['S1','S2'], description: '')
    }
    tools {
      maven 'Maven-3.8.1'
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh "chmod +x -R ${env.WORKSPACE}"
                sh './jenkins/scripts/deliver.sh'
                echo "Deploying ${params.version} to ${params.deploymentServer}"
            }
        }
    }
}
